#!/bin/bash 
    
echo $$ > ~/pid

list=~/.listmusic
upcoming=~/.upcomingmusic

mplayerfifo=/tmp/mplayerfifo
stoploop=/tmp/stoploop

playing=/tmp/playing
prev=/tmp/prev

pref=~/.mmusicpref

function play {
    echo "quit" > "$mplayerfifo"
    sleep 0.25 
    echo "$1" > "$playing"
}

function startplaying {
    if [ -a "$mplayerfifo" ]
    then
        rm "$mplayerfifo"
    fi

    if [ -a "$playing" ]
    then
        rm "$playing"
    fi

    mkfifo "$mplayerfifo"
    touch "$playing"

    for (( ; ; ))
    do
        song=`cat "$playing"`
        if [ -z "$song" ]
        then
            song=`$0 getrandom`
            echo "$song" > "$playing"
        fi

        mplayer -really-quiet -slave -input file="$mplayerfifo" "$song"
        echo "$song" > "$prev"

        next=`cat "$upcoming" | head -1`
        echo "$next" > "$playing"

        tail -n +2 "$upcoming" > /tmp/tmpupcoming
        cat /tmp/tmpupcoming > "$upcoming"
        rm /tmp/tmpupcoming

        if [ -a "$stoploop" ]
        then
            break
        fi

        sleep 0.5
    done

    rm "$playing"
    rm "$mplayerfifo"
}

function getrandom {
    RAND=`od -d -N2 -An /dev/urandom`
    LINES=`cat "$list" | wc -l`
    N=$(( RAND % LINES + 1 ))
    LINE=`head -$N $list | tail -1`
    echo "$LINE"
}

function skip {
    next=`cat "$upcoming" | head -1`
    echo "$next" > "$playing"
    echo "q" > "$mplayerfifo"
}

function prev {
    song=`cat "$prev"`
    play "$song"
}

function exitd {
    touch "$stoploop"
    echo "quit" > "$mplayerfifo"

    if [ -n "$2" ]
    then
        sleep $(($2 - 0.5))
    fi

    sleep 0.5

    if [ -a "$mplayerfifo" ] 
    then 
        rm "$mplayerfifo"
    fi

    rm "$stoploop"
}

function addfolder {
    find "$2" -name "*.*" >> "$1"
}

function addfile {
    echo "$2" >> "$1"
}

function sortlist {
    sort -f "$list" | uniq > "/tmp/sorting"
    cat "/tmp/sorting" > "$list"
    rm "/tmp/sorting"
}

function add {
    file="$upcoming"
    command="addfile"
    
    for arg in "$@"
    do
        if [ "$arg" == "add" ]; then
            continue
        elif [ "$arg" == "list" ]; then
            file="$list"
        elif [ "$arg" == "upcoming" ]; then
            file="$upcoming"
        elif [ "$arg" == "random" ]; then
            echo "$(getrandom)" >> "$file"
        elif [ "$arg" == "file" ]; then
            command="addfile"
        elif [ "$arg" == "folder" ]; then
            command="addfolder"
        else
            "$command" "$file" "$arg"
        fi
    done

    if [ "$file" == "$list" ]; then
        sortlist
    fi
}

if [ "$1" == "play" ]
then
    play
fi

if [ -z "$1" ]
then
    startplaying &
fi

if [ "$1" == "getrandom" ]
then
    getrandom
fi

if [ "$1" == "clear" ]
then
    rm "$upcoming"
    touch "$upcoming"
fi

if [ "$1" == "skip" ]
then
    skip
fi

if [ "$1" == "prev" ]
then
    prev
fi

if [ "$1" == "stop" ]
then
    exitd 
fi

if [ "$1" == "add" ]
then 
    add "$@"
fi

if [ "$1" == "playing" ]
then
    if [ -a "$playing" ]
    then
        cat "$playing"
    fi
fi

if [ "$1" == "upcoming" ]
then
    echo "$upcoming"
fi

if [ "$1" == "list" ]
then
    echo "$list"
fi

if [ "$1" == "pause" ]
then
    echo "pause" > "$mplayerfifo"
fi

if [ "$1" == "preffile" ]
then
    echo "$pref"
fi
